# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
reviews:
  request_changes_workflow: true
  review_status: true
  review_progress: true
  fail_commit_status: true
  auto_review:
    enabled: true
    drafts: true
    auto_incremental_review: true
    auto_pause_after_reviewed_commits: 0
